[package]
name = "tools"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["grpc"]
grpc = ["dep:tonic", "dep:oprc-grpc"]
loadtest = [
    "dep:rlt","dep:anyhow", "dep:oprc-grpc", "dep:serde_json",
]
all = ["loadtest", "grpc"]

[dependencies]
anyhow = {workspace = true, optional = true}
async-trait = {workspace = true}
clap = { workspace = true}
clap-stdin = {workspace = true}
envconfig = {workspace = true}
flume = { workspace = true }
oprc-grpc ={ workspace=true ,  optional = true}
oprc-zenoh ={ workspace = true}
oprc-invoke = {workspace = true}
prost = {workspace = true, features = ["derive"]}
rand = {workspace = true}
rlt = {workspace = true, optional = true}
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic = { workspace=true , optional = true}
tracing = {workspace = true}
tracing-subscriber = { workspace = true}
serde_json = {workspace = true, optional = true}
zenoh = {workspace = true, features = ["unstable"]}
zenoh-config = {workspace = true}



[[bin]]
name = "bench-kv-set"
required-features = ["loadtest"]

[[bin]]
name = "bench-kv-get"
required-features = ["loadtest"]

[[bin]]
name = "bench-no-op"
required-features = ["loadtest"]

[[bin]]
name = "bench-z-invoke"
required-features = ["loadtest"]

[[bin]]
name = "bench-g-invoke"
required-features = ["loadtest", "grpc"]


[[bin]]
name = "bench-z-invoke-origin"
required-features = ["loadtest"]

[[bin]]
name = "bench-z-invoke-stateful"
required-features = ["loadtest"]