image:
  repository: ghcr.io/pawissanutt/oaas-rs/crm
  pullPolicy: Always
  tag: "dev-alpha"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

router:
  resources:
    # limits:
    #   cpu: "8"
    #   memory: "512Mi"
    requests:
      cpu: "0.25"
      memory: "256Mi"
  zenoh:
    peers: "tcp/oaas-crm-1-oprc-crm-router.oaas-1.svc.cluster.local:17447"
# Scope CRM-2 to namespace oaas-2 and use it for default operations
config:
  namespace: oaas-2