plugins:
  - victoriametrics-logs-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      url: http://vm-single-victoria-metrics-single-server.observability.svc.cluster.local:8428
      access: proxy
      isDefault: true
    - name: VictoriaLogs
      type: victoriametrics-logs-datasource
      url: http://vm-logs-victoria-logs-single-server.observability.svc.cluster.local:9428
      access: proxy
      isDefault: false
    - name: VictoriaTraces
      type: jaeger
      url: http://vm-traces-vt-single-server.observability.svc.cluster.local:10428/select/jaeger
      access: proxy
      isDefault: false
      jsonData:
        tracesToLogsV2:
          datasourceUid: VictoriaLogs
        tracesToMetrics:
          datasourceUid: VictoriaMetrics
